### ISSUE TITLE
Missing 'removePreviousSessions' function on SessionRecord class

### ISSUE THREAD

**Issue by malufett** [ForstaLabs/libsignal-node#4]
this function is missing and its causing an issue on updating sessions..
![image](https://user-images.githubusercontent.com/3251821/38052251-a23c08cc-329e-11e8-866d-4386c6842231.png)
it was used in this line
![image](https://user-images.githubusercontent.com/3251821/38052278-b7230af6-329e-11e8-9178-4924443ff80b.png)

**Comment by mayfield** [comment]
Thank you.  Should be fixed now.  Version 1.2.2 in NPM should have the fix too.
