### ISSUE TITLE
__dirname not working

### ISSUE THREAD

**Issue by ghbutton** [ForstaLabs/libsignal-node#5]
When using your library with electron I get an error because __dirname is defined as '/' and the script in protobufs.js cannot load the correct file

**Comment by ghbutton** [comment]
I think it is more because I am using react-scripts from create-react-app

**Comment by mayfield** [comment]
Does that mean your root folder is the `src/` directory?  You'll need a parent folder that contains the `protos` dir for it to function properly.  Tbuild env issue?

**Comment by ghbutton** [comment]
I created the simplest electron app following this blog post: https://medium.freecodecamp.org/building-an-electron-application-with-create-react-app-97945861647c

And then I included a file (project/src/Controller.js) which `require('libsignal');`

I think the create-react-app somehow overrides the __dirname and I get a file not found error

**Comment by mayfield** [comment]
I'll see if I can't repro this weekend.  In the meantime if you manage to identify what the actual FS layout is inside that electron sandbox or an alternative to `__dirname` (which I'd happily take a PR for), let me know.

**Comment by ghbutton** [comment]
thanks, I will keep trying. So far the only solution I have found is to hard code the path

**Comment by mayfield** [comment]
Are you by chance using webpack on the node modules? 

See: https://codeburst.io/use-webpack-with-dirname-correctly-4cad3b265a92

I still think there might be something amiss in your env.  It also looks like webpack and electron have a troubled history with `__dirname`;  I'm going to hold off on merging your pull request (#6) as it makes some assumptions about `/` being a special directory and the `module.i` property is not one that resolves in my system;  So something isn't right.  That guide is too involved for me to get into, so I'm going to apply a small compatibility change to the usage of `__dirname` in that module and you might try messing with the electron options in your setup, as per that link above (namely the `__dirname: false` option).

**Comment by mayfield** [comment]
@ghbutton what version of node are you using?  I see some internet chatter about `__dirname` behavior being different for the new ECMAScript modules (https://nodejs.org/api/esm.html).  Looks like it's still experimental but perhaps electron and/or your react env are turning that on.  There might be a technique I can use that's compatible with this new module system, so let me know.

**Comment by ghbutton** [comment]
I am using version 11.8.0

**Comment by ghbutton** [comment]
Yea, I think it might be an electron issue of some kind

**Comment by ghbutton** [comment]
thank you
