### ISSUE TITLE
But how does it work?

### ISSUE THREAD

**Issue by Redsandro** [ForstaLabs/libsignal-node#7]
Did I miss something? Instructions on how to use this in `node.js`?
Would appreciate some extra notes or an example in `README.md`.

**Comment by andydixon** [comment]
It's quite cryptic with no example code. If the author would be able to add some sort of example that would be appreciated!

**Comment by mayfield** [comment]
Hey guys,  This is a direct port of the libsignal-javascript library for whispersystems.  Which is a very low level library.  You need a lot more than this library to build out support for a signal stack.  We're an extremely small startup (4 devs with focus on mobile) so we simply don't have the resources to maintain docs for this guy, BUT I can say this lib hardly ever changes and I recommend you check out the README from the forked javascript project (which really is designed for use in a web browser): https://github.com/signalapp/libsignal-protocol-javascript/blob/master/README.md  as well as our higher level abstraction which sits on top of this lib, https://github.com/ForstaLabs/librelay-node .  Bear in mind that is a code base for our signal fork, not the public signal ecosystem.  We host our own signal based messaging platform.

Sorry we can't do any better for now.  Hopefully we can come back to this lib and give it some much needed docs.

**Comment by Redsandro** [comment]
Thank you for getting back at us @mayfield. 

In order to prevent this from happening again with other humans, you may want to consider writing exactly what you just said (or abridged) in this project's README.md. Or just:

> This is a direct port of the libsignal-javascript library for whispersystems. See https://github.com/signalapp/libsignal-protocol-javascript/blob/master/README.md
